In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [3]:
len(words)

32033

In [4]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [40]:
block_size = 3
X, Y = [], []
for w in words[:5]:
    print(w)
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '---->', itos[ix])
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ----> e
..e ----> m
.em ----> m
emm ----> a
mma ----> .
olivia
... ----> o
..o ----> l
.ol ----> i
oli ----> v
liv ----> i
ivi ----> a
via ----> .
ava
... ----> a
..a ----> v
.av ----> a
ava ----> .
isabella
... ----> i
..i ----> s
.is ----> a
isa ----> b
sab ----> e
abe ----> l
bel ----> l
ell ----> a
lla ----> .
sophia
... ----> s
..s ----> o
.so ----> p
sop ----> h
oph ----> i
phi ----> a
hia ----> .


In [41]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [42]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [7]:
C = torch.randn((27, 2))

In [ ]:
C, 

(tensor([[-1.3372, -0.7498],
         [ 0.8279, -0.0316],
         [ 0.4273, -1.3758],
         [ 0.3352, -0.0783],
         [-1.2044,  0.5711],
         [ 1.8827,  0.2453],
         [ 0.0735, -1.8913],
         [-0.8697,  1.3671],
         [ 0.3187,  0.2224],
         [ 0.2000, -1.7976],
         [ 0.3067, -0.8966],
         [-0.8014, -0.1018],
         [ 1.1383,  1.6382],
         [ 0.5470,  1.8112],
         [ 0.7187,  0.1389],
         [-1.3366, -0.6726],
         [-1.3384, -2.5148],
         [ 0.4933,  0.6044],
         [-0.1129,  0.8706],
         [-1.3882,  2.4827],
         [-0.3815,  0.2480],
         [-1.1160,  1.1106],
         [-0.5969, -0.3790],
         [-1.6956,  1.1013],
         [ 1.3383, -0.1627],
         [ 0.8726,  1.3840],
         [ 0.1311, -0.1932]]),
 tensor([[ 0,  0,  0],
         [ 0,  0,  5],
         [ 0,  5, 13],
         [ 5, 13, 13],
         [13, 13,  1],
         [ 0,  0,  0],
         [ 0,  0, 15],
         [ 0, 15, 12],
         [15, 12,  9],
        

In [11]:
C[5]

tensor([1.8827, 0.2453])

In [13]:
emb = C[X]
emb.shape

torch.Size([32, 3, 2])

In [ ]:
w1 = torch.randn((6, 100))
b1 = torch.randn(100)

In [26]:
# torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], dim=1).shape

In [27]:
# torch.cat(torch.unbind(emb, 1), 1).shape

In [28]:
# a = torch.arange(18)
# # a

In [29]:
# a.view()

In [43]:
h = torch.tanh(emb.view(-1, 6) @ w1 + b1)
h

tensor([[ 0.9101,  0.9999,  0.8945,  ...,  0.6493,  0.8319,  0.9377],
        [ 0.9938,  0.9997,  0.6532,  ...,  0.9790, -0.6698,  1.0000],
        [-0.9771,  0.9984,  0.9962,  ...,  0.9998,  0.9321, -0.9796],
        ...,
        [ 0.9996,  0.9999,  0.9951,  ...,  0.1904, -0.5284,  1.0000],
        [-0.9987,  0.9988, -0.3895,  ...,  0.9950,  0.9587, -0.8784],
        [ 0.9925, -0.5053, -0.3185,  ..., -0.3333, -0.9123,  1.0000]])

In [44]:
h.shape

torch.Size([32, 100])

In [47]:
w2 = torch.randn((100, 27))
b2 = torch.randn(27)

In [48]:
logits = h @ w2 + b2

In [49]:
logits.shape

torch.Size([32, 27])

In [50]:
counts = logits.exp()

In [51]:
prob = counts / counts.sum(1, keepdim=True)

In [52]:
prob.shape

torch.Size([32, 27])

In [55]:
loss = -prob[torch.arange(32), Y].log().mean()
loss

tensor(19.6656)